name: Build Android APK

on:
  push:
    branches: [ "main", "master" ] # ทำงานเมื่อมีการ push โค้ดเข้า branch main หรือ master
  workflow_dispatch: # กดสั่งรันเองได้จากหน้าเว็บ GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout Source Code
      uses: actions/checkout@v4

      
name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu' # ใช้ Zulu JDK ที่มีความเสถียรสูง
        cache: 'gradle'

      
name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

      
name: Install Dependencies
      run: npm install

      
name: Build Web Project
      run: npm run build

      
name: Sync Capacitor
      run: npx cap sync android

      
name: Build Android APK
      working-directory: android
      run: |
        chmod +x gradlew./gradlew assembleDebug

      
name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk